backend/billing/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (
    charge_point,
    PointCheckoutAjaxView,
    PointImpAjaxView,
)
app_name= 'billing'

urlpatterns = [
    url('charge/', charge_point),
    url('checkout/', PointCheckoutAjaxView.as_view(), name='point_checkout'),
    url('validation/', PointImpAjaxView.as_view(), name='point_validation'),
]

backend/config/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import (include, path)

# from allauth.views import ConfirmEmailView

# Swagger
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework.permissions import AllowAny

schema_url_patterns = [
    path('account/', include('sign.urls')),
    path('party/', include('party.urls')),
    path('billing/', include('billing.urls')),
    path('movies/', include('rec_movie.urls')),
    path('programs/', include('rec_program.urls')),
    ]

schema_view_v1 = get_schema_view(
    openapi.Info(
        title="BackEnd API",
        default_version='v1',
        description="시스템 API",
        terms_of_service="https://www.google.com/policies/terms/",
    ),
    public=True,
    permission_classes=(AllowAny,),
    patterns=schema_url_patterns,
)

urlpatterns = [
    # silk 적용
    path('silk/', include('silk.urls')),

    path('api/v1/admin/', admin.site.urls),
    path('api/v1/party/', include('party.urls')), # Party
    path('api/v1/account/', include('sign.urls')), # User
    path('api/v1/billing/', include('billing.urls')),
    path('api/v1/movies/', include('rec_movie.urls')),  # Movie contents
    path('api/v1/programs/', include('rec_program.urls')),  # Program contents

    # Swagger 연동
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view_v1.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view_v1.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view_v1.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

backend/sign/urls.py
from django.urls import (include, path)
from rest_framework import routers
from dj_rest_auth.views import (
    LoginView, LogoutView, PasswordChangeView,
    UserDetailsView, PasswordResetView,
    PasswordResetConfirmView
)
from dj_rest_auth.registration.views import RegisterView
from . import views

router = routers.DefaultRouter()
router.register('', views.UserMe)

urlpatterns = [
  # rest-auth 로그인/로그아웃/프로필
  path('login/', LoginView.as_view(), name='rest_login'),
  path('logout/', LogoutView.as_view(), name='rest_logout'),
  path('register/', RegisterView.as_view(), name='rest_register'),
  # path('profile/', UserDetailsView.as_view(), name='detail'),
  path('me/', include(router.urls), name='me'),
  path('profile/<int:pk>/', views.UserProfileView.as_view(), name='profile'),
  path('profile/genres/', views.FavGenreView.as_view()),

  # 회원가입, 비밀번호 변경
  path('password/reset/', PasswordResetView.as_view(), name='rest_password_reset'),
  path('password/reset/confirm/uid=<int:uid>&token=<str:token>/', views.passwordResetRedirect, name='password_reset_confirm'),
  path('password/reset/confirm/', PasswordResetConfirmView.as_view(), name='rest_password_reset_confirm'),
  path('password/change/', PasswordChangeView.as_view(), name='rest_password_change'),
  # google oauth
  path('google/callback/', views.google_callback, name='google_callback'),
  path('google/login/finish/', views.GoogleLogin.as_view(), name='google_login_to_django'),
  # kakao oauth
  path('kakao/callback/', views.kakao_callback, name='kakao_callback'),
  path('kakao/login/finish/', views.KakaoLogin.as_view(), name='kakao_login_to_django'),
  # github oauth
#   path('github/callback/', views.github_callback, name='github_callback'),
#   path('github/login/finish/', views.GithubLogin.as_view(), name='github_login_to_django'),
#   # naver oauth
#   path('naver/callback/', views.naver_callback, name='naver_callback'),
#   path('naver/login/finish/', views.NaverLogin.as_view(), name='naver_login_to_django'),
]

backend/billing/models.py
import time
import random
import hashlib

from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from billing.iamport import validation_prepare, get_transaction, get_access_token
from party.models import Party

# 유저가 결제를 시도한 정보
class Point(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  pay = models.PositiveIntegerField(default=0)
  created = models.DateTimeField(auto_now_add=True, auto_now=False)
  timestamp = models.DateTimeField(auto_now_add=False, auto_now=True)

  def __str__(self):
    return str(self.pay)

# class PointItems(models.Model):
#   order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
#   party = models.ForeignKey(Party, on_delete=models.PROTECT, related_name='order_party')
#   price = models.DecimalField(max_digits=10, decimal_places=2)
   
#   def __str__(self):
#     return '{}.'.format(self.id)
  
#   def get_item_price(self):
#     return self.price

class PointTransactionManager(models.Manager):
  def create_new(self, user, amount, type, success=None, transaction_status=None):
    if not user:
      raise ValueError('유저가 확인되지 않습니다.')
    if user:
      raise ValueError('test')
    short_hash = hashlib.sha1(str(random.random())).hexdigest()[:2]
    time_hash = hashlib.sha1(str(int(time.time()))).hexdigest()[-3:]
    base = str(user.email).split('@')[0]
    key = hashlib.sha1(short_hash + time_hash + base).hexdigest()[:10]
    new_order_id = "%s" % (key)

    # 아임포트 결제 사전 검증 단계
    validation_prepare(new_order_id, amount)

    new_trans = self.model(
      user=user,
      order_id=new_order_id,
      amount=amount,
      type=type,
    )
    print(success + 'success')
    if success is not None:
      new_trans.sucess = success
      new_trans.transaction_status = transaction_status

    new_trans.save(using=self._db)

    return new_trans.order_id

  def validation_trans(self, merchant_id):
    result = get_transaction(merchant_id)
    
    if result['status'] == 'paid':
      return result
    else:
      return None

  def all_for_user(self, user):
    return super(PointTransactionManager, self).filter(user=user)

  def get_recent_user(self, user, num):
    return super(PointTransactionManager, self).filter(user=user)[:num] 


# 결제 모듈을 통해 결제가 이루어지는 정보를 담는 모델
class PointTransaction(models.Model):
  user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
  transaction_id = models.CharField(max_length=120, null=True, blank=True) # 아임포트에서 생성해주는 고유 번호
  order_id = models.CharField(max_length=120, unique=True) # 서버 내에서 자동으로 생성하는 주문 번호
  amount = models.PositiveIntegerField(default=0)
  success = models.BooleanField(default=False)
  transaction_status = models.CharField(max_length=220, null=True, blank=True)
  type = models.CharField(max_length=120)
  created = models.DateTimeField(auto_now_add=True, auto_now=False)

  objects = PointTransactionManager()

  def __str__(self):
    return self.order_id

  class Meta:
    ordering = ['-created']

def new_point_trans_validation(sender, instance, created, *args, **kwargs):

  if instance.transaction_id:
    # 거래 후 아임포트에서 넘긴 결과
    v_trans = PointTransaction.objects.validation_trans(
      merchant_id=instance.order_id
    )

    res_merchant_id = v_trans['merchant_id']
    res_imp_id = v_trans['imp_id']
    res_amount = v_trans['amount']

    # 데이터베이스에 실제 결제된 정보가 있는지 체크
    r_trans = PointTransaction.objects.filter(
      order_id=res_merchant_id,
      transaction_id=res_imp_id,
      amount=res_amount
    ).exists()

    if not v_trans or not r_trans:
      raise ValueError('비정상적인 거래입니다.')


post_save.connect(new_point_trans_validation, sender=PointTransaction)

backend/billing/forms.py
from django import forms

from .models import Order

class OrderCreateForm(forms.ModelForm):
  
    class Meta:
        model = Order
        fields = '__all__'

backend/billing/views.py
from django.shortcuts import render
from django.http import JsonResponse
from rest_framework.response import Response
from .models import (
  PointTransaction, 
  Point,
)
from rest_framework.views import APIView
from django.views.generic.base import View

class PointCheckoutAjaxView(APIView):

  def post(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      return JsonResponse({}, status=401)

    user = request.user
    print(user)
    amount = request.POST.get('amount')
    print(amount)
    type = request.POST.get('type')
    print(type)
    try:
      trans = PointTransaction.objects.create_new(
        user=user,
        amount=amount,
        type=type
      )
    except:
      trans = None
    print(trans)
    if trans is not None:
      data = {
        "works": True,
        "merchant_id": trans
      }
      return JsonResponse(data)
    else:
      return JsonResponse({}, status=401)

class PointImpAjaxView(APIView):
  def post(self, request, *args, **kwargs):
    if not request.user.is_authenticated:
      return JsonResponse({}, status=401)

    user = request.user
    merchant_id = request.POST.get('merchant_id')
    imp_id = request.POST.get('imp_id')
    amount = request.POST.get('amount')

    try:
      trans = PointTransaction.objects.get(
        user=user,
        order_id=merchant_id,
        amount=amount
      )
    except:
      trans = None

    if trans is not None:
      trans.transaction_id = imp_id
      trans.success = True
      trans.save()

      data = {
        "works": True
      }

      return JsonResponse(data)
    else:
      return JsonResponse({}, status=401)

def charge_point(request):
  template = 'charge.html'

  return render(request, template)

backend/billing/templates/charge.html
{% load static %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>디제이비버</title>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js"></script>
    <script type="text/javascript" src="https://service.iamport.kr/js/iamport.payment-1.1.1.js"></script>
    <script type="text/javascript">
        $(function () {
            var IMP = window.IMP;
            // 가맹점 코드
            IMP.init('imp84302854');

            $('.charge-button').on('click', function (e) {
                var amount = parseInt($('.charge-total #total').text().replace(',', '').slice(0, -1));
                var type = $('.charge-type input:checked').val();
                var merchant_id = AjaxStoreTransaction(e, amount, type);

                if (merchant_id !== '') {
                    IMP.request_pay({
                        // pg: 'html5_inicis',
                        escrow: false,
                        digital: true,
                        pay_method: type,
                        merchant_uid: merchant_id,
                        name: '포인트' + amount + '원 충전',
                        amount: amount
                    }, function (rsp) {
                        if (rsp.success) {
                            var msg = '결제가 완료되었습니다.';
                            msg += '고유ID : ' + rsp.imp_uid;
                            msg += '상점 거래ID : ' + rsp.merchant_uid;
                            msg += '결제 금액 : ' + rsp.paid_amount;
                            msg += '카드 승인번호 : ' + rsp.apply_num;
                            ImpTransaction(e, rsp.merchant_uid, rsp.imp_uid, rsp.paid_amount);
                        } else {
                            var msg = '결제에 실패하였습니다.';
                            msg += '에러내용 : ' + rsp.error_msg;
                            console.log(msg);
                        }
                    });
                }
            });
        });

        function AjaxStoreTransaction(e, amount, type) {
            e.preventDefault();
            console.log(amount)
            var merchant_id = '';
            var request = $.ajax({
                method: "POST",
                url: '{% url "billing:point_checkout" %}',
                async: false,
                data: {
                    amount: amount,
                    type: type,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                }
            });
            console.log(request)
            request.done(function (data) {
                if (data.works) {
                    merchant_id = data.merchant_id;
                }
            });
            request.fail(function (jqXHR, textStatus) {
                if (jqXHR.status == 404) {
                    alert("페이지가 존재하지 않습니다.");
                } else if (jqXHR.status == 403) {
                    alert("로그인 해주세요.");
                } else {
                    alert("문제가 발생. 다시 시도해주세요.");
                }
            });
            return merchant_id;
        }

        function ImpTransaction(e, merchant_id, imp_id, amount) {
            e.preventDefault();
            var request = $.ajax({
                method: "POST",
                url: '{% url "billing:point_validation" %}',
                async: false,
                data: {
                    merchant_id: merchant_id,
                    imp_id: imp_id,
                    amount: amount,
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                }
            });
            request.done(function (data) {
                if (data.works) {
                }
            });
            request.fail(function (jqXHR, textStatus) {
                if (jqXHR.status == 404) {
                    alert("페이지가 존재하지 않습니다.");
                } else if (jqXHR.status == 403) {
                    alert("로그인 해주세요.");
                } else {
                    alert("문제가 발생했습니다. 다시 시도해주세요.");
                }
            });
        }
    </script>
</head>
<body>

{% if user.is_authenticated %}
    {{ user }}으로 접속되어 있습니다.
{% else %}
    로그인 해주세요!
{% endif %}

    <div class="charge-type">
        <div class="billing-title">
            결제방식
        </div>
        <div class="billing-radio">
            <label class="control control--radio">
                <input type="radio" name="type" value="card" checked="checked"/>
                신용카드
            </label>
            <label class="control control--radio">
                <input type="radio" name="type" value="trans"/>
                실시간 계좌이체
            </label>
            <label class="control control--radio">
                <input type="radio" name="type" value="phone"/>
                휴대폰
            </label>
            <label class="control control--radio">
                <input type="radio" name="type" value="vbank"/>
                가상계좌 입금
            </label>
        </div>
    <div>
    <div class="charge-total">
        총 결제금액 <span id="total">1000원</span>
    </div>
    <div class="charge-click">
        <button class="charge-button">충전하기</button>
    </div>
</body>
</html>